"""empty message

Revision ID: 70953c107e2d
Revises: adcb0c15085a
Create Date: 2026-03-13 02:07:08.509989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70953c107e2d'
down_revision = 'adcb0c15085a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
